### ISSUE TITLE
Cannot open "Connection Settings"

### ISSUE THREAD

**Issue by mueckinger** [SJBERTRAND/portforwarding-extension#1]
Would love to use this extension, but I cannot open the settings on Gnome 46.
OS: Ubuntu 24.04 LTS

`The settings of extension portforwarding-extension@SJBERTRAND.github.com had an error:
```
Error: Requiring Vte, version none: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Vte/:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```
`

**Comment by SJBERTRAND** [comment]
Hi mueckinger,
thanks for letting me know as I do not use Ubuntu.
I made a quick fix right now which remove the first connection button from the settings. I was trying to be fancy and turns out that not all distro have Lib VTE 3.91.  Anyway, if you want to fix this now, in the git repository there is now a folder named ubuntu-fix inside there is a file name pref.js. Copy this file and replace the one located @ ~/.local/share/gnome-shell/extensions/portforwarding-extension@SJBERTRAND.github.com/

I will update the extension on the gnome-extension website soon. Let me know if it works or if there is something else.

**Comment by mueckinger** [comment]
Update to Version 2.0 was shown minutes later in the gnome extension-manager. That's fast! 
And it works.
Great work, thank you!
